name: Save Websites as HTML

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

permissions:
  contents: write

jobs:
  save_websites:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Save Website 1 (index.html)
        run: |
          curl -L -o index.html https://www.grayscale.com/crypto-products/grayscale-bitcoin-cash-trust

      - name: Save Website 2 (ltcn.html)
        run: |
          curl -L -o ltcn.html https://www.grayscale.com/crypto-products/grayscale-litecoin-trust

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Save websites HTML"
          file_pattern: '*.html'
          branch: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
