name: Save Websites as HTML

on:
  schedule:
    - cron: '30 14 * * 1-5'  # Monday to Friday at 14:30 UTC
    - cron: '0 18 * * 1-5'   # Monday to Friday at 18:00 UTC
    - cron: '0 21 * * 1-5'   # Monday to Friday at 21:00 UTC
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  save_websites:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Save Website 1 (index.html)
        run: |
          curl -L -o index.html https://example1.com  # Replace example1.com with the first website URL you want to save

      - name: Save Website 2 (ltcn.html)
        run: |
          curl -L -o ltcn.html https://example2.com  # Replace example2.com with the second website URL you want to save

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Save websites HTML"
          file_pattern: '*.html'
          branch: ${{ github.ref }}
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
